### ISSUE TITLE
%Z doesn't recognize Z without offset

### ISSUE THREAD

**Issue by splunkericl** [itchyny/timefmt-go#6]
`ParseInLocation` doesn't recognize string format that has `Z` without offset and returns error.

### Steps to reproduce
- call `timefmt.ParseInLocation("2023-06-28T16:30:00Z", "%Y-%m-%dT%H:%M:%S%Z", time.UTC)`

### Expected Results
- no error is returned
- time is returned and set to June 28, 16:30 UTC

### Actual Results
- error is returned `failed to parse "2023-06-28T16:30:00Z" with "%Y-%m-%dT%H:%M:%S%Z": cannot parse "Z" with "%Z"`

### Additional context
- This time would somehow work with `%z`. For example `timefmt.ParseInLocation("2023-06-28T16:30:00Z", "%Y-%m-%dT%H:%M:%S%z", time.UTC)` returns no error and the correct time

**Comment by splunkericl** [comment]
Hello @itchyny, can you check if this issue and PR makes sense? Thanks.

**Comment by itchyny** [comment]
This doesn't make sense to me. `Z` is a zone offset, not a timezone name.

**Comment by splunkericl** [comment]
But in ISO 8601 standard, the `Z` on the end means UTC(offset-from-UTC of zero). Here is a related stackoverflow [answer](https://stackoverflow.com/questions/8405087/what-is-this-date-format-2011-08-12t201746-384z). 

Isn't this the assumption with `%z` as well that is why having the `Z` in the end works for `%z`?

**Comment by itchyny** [comment]
Yes, `Z` is the zero UTC offset. `Z` is a zone offset just like `+01:00` is, and `UTC` is a timezone name just like `PST` is. That's why `%z` parses `Z` and `+01:00`, and `%Z` parses `UTC` and `PST`. But `%Z` does not parse `Z` and `%z` does not parse `UTC`.

**Comment by splunkericl** [comment]
ok I see. so the reasoning is `Z` represents hours offset, which is what `%z` handles. This makes sense now. Thanks for clarifying.
