### ISSUE TITLE
could you support parsing timestamps of millisecond and nanosecond types

### ISSUE THREAD

**Issue by veritaspei** [itchyny/timefmt-go#9]
could you support parsing timestamps of millisecond and nanosecond types, such as: 1571394459123 or 1571394459123456?

**Comment by itchyny** [comment]
What format directive do you think is suitable for this?

**Comment by veritaspei** [comment]
May be %q for millisecond, %Q for microsecond, compatibility needs to be considered.

**Comment by itchyny** [comment]
I checked [strptime(3)](https://linux.die.net/man/3/strptime) and [Python datetime](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) but I can't find them. Do you know any platform supporting these directive?

**Comment by veritaspei** [comment]
I find out that Tencent Cloud supports them(%F for microsecond and %q for microsecond). But actually %F is used by strptime.
![image](https://github.com/itchyny/timefmt-go/assets/29913537/c4a84561-6309-42ac-87a8-886f65660ff8)

**Comment by itchyny** [comment]
I'm not going to implement non-standard format directives in this package. If you want to parse a string with unix timestamp alone, I recommend to convert it to integer with `strconv.ParseInt`, and to `time.Time` with `time.UnixMicro`. That's much better in performance.

**Comment by veritaspei** [comment]
ok, thank you.
